### ISSUE TITLE
How to ignore the hidden mesh when the mouse detects it .

### ISSUE THREAD

**Issue by pxim** [HomeSmartMesh/web_three_interface#3]
How to ignore the hidden mesh when the mouse detects it .
ignore the mesh with `visible===false `

![image](https://user-images.githubusercontent.com/5111701/126587306-25d2d9cd-da5d-4c31-8398-502e32c1dace.png)
![image](https://user-images.githubusercontent.com/5111701/126587378-6e54e04c-5a8b-4c96-b888-168358b73090.png)

**Comment by wassfila** [comment]
I tried to understand your example but it was a bit hard for me to match it with this repo, can you maybe link to the source with the line menu `Copy permalink` instead of screenshot ?
Also is it an issue you reproduced with this or another repo ? I would try to help in both cases but I need somehow to reproduce the issue before I can properly analyze it, if you have a minimal example for it ?

![image](https://user-images.githubusercontent.com/1510763/127026206-12228ab7-83c3-4d70-842a-f120dda2b828.png)

**Comment by pxim** [comment]
> I tried to understand your example but it was a bit hard for me to match it with this repo, can you maybe link to the source with the line menu `Copy permalink` instead of screenshot ?
> Also is it an issue you reproduced with this or another repo ? I would try to help in both cases but I need somehow to reproduce the issue before I can properly analyze it, if you have a minimal example for it ?
> 
> ![image](https://user-images.githubusercontent.com/1510763/127026206-12228ab7-83c3-4d70-842a-f120dda2b828.png)

I solved the problem .
need traverse the hidden object and all of its children’s layers ,
make their layers inconsistent with the camera’s layers.

reference example
https://jsfiddle.net/eL689k74/23/

**Comment by wassfila** [comment]
Cool, glad to hear you solved it and thanks for the fiddle, now I understood better your example :)
